---
output:
  bookdown::pdf_document2:
    keep_tex: true
    fig_caption: true
    latex_engine: xelatex
    number_sections: true
  bookdown::word_document2:
    reference_docx: "template_CHN.docx"
    keep_md: true
    number_sections: FALSE
knit: (function(inputFile, encoding) {rmarkdown::render(inputFile, encoding = encoding, output_format = c("bookdown::word_document2", "bookdown::pdf_document2")) })
documentclass: ctexart

fontsize: 12pt
geometry: margin=1in
# bibliography: /Users/sunyufei/Desktop/Zotero.bib
# csl: "paper/china-national-standard-gb-t-7714-2015-author-date.csl"
link-citations: true
colorlinks: true
toc: false

editor_options: 
  markdown: 
    wrap: sentence

title: '政策扩散与政府间关系'

author:
- 孙宇飞^[清华大学政治学系博士生，联系电话：18638750921，邮箱：sunyf20@mails.tsinghua.edu.cn]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
if (!require(pacman)) install.packages("pacman")
library(pacman)
p_load(grid,
       gridExtra,
       png,
       magick, 
       usmap,
       interplot,
       dotwhisker,
       modelsummary,
       # Visualization
       lubridate,
       # Applied
       broom,
       knitr,
       # dependency
       scales,
       tidyverse,
       drhutools,
       qs)
set.seed(19970921)
# Theme setup
theme_set(theme_minimal())
#Data input
```

# 政策扩散与政府间关系

## 扩散概念

### 概念界定与演变

- 定义方式与来源（中/英）

（图1 ngram 中/英文，web of science）

- 概念演变

（图2 词与词关系*时间）

### 临近概念辨析

- 政策扩散与政策转移，政策学习

- 政策扩散与技术扩散

### 政策扩散代表性和特殊性

+ 政策扩散包含decision maker, policy and policy implication
+ 政策扩散兼具时效性和长期性

### 政策扩散研究的聚类分析（why doing this? what do you wanna show?）


## 扩散主体

### 内部主体

- 内部行动者的类别

- 内部行动者如何影响政策扩散

  - 偏好
  
  - 目标
  
  - 能力
  
  - 和其他行动者的互动

### 外部主体

- 外部行动者的类别

  - 中央政府
  
  - 其他地方政府
  
  - 其他国家和超国家组织
  
  - 政策企业家


## 扩散内容

### 常规政策扩散

- 福利政策

- 教育政策

- 公民权利政策

### 非常规政策的扩散

- 制度扩散

- 体制扩散

- 骚乱和政变的扩散


## 扩散逻辑

这部分分类不好，不够理论，看我改的，再做修改

### 策略性扩散（Strategic action）

### 时效性扩散（Common shock）

### 相似导致扩散（Homophily）


## 扩散路径 (要和上面做好区分)

### 学习机制

- 谁来学

  - 横向的学习
  
  - 纵向的学习

- 学什么

  - 正向学习
  
  - 负向学习

- 怎么学
  
  - 什么是成功的政策
  
  - 如何识别政策成功

### 竞争机制

- 怎么竞争

- 竞争的后果

  - 竞争的正向效应
  
  - 负向的负向效应

### 强制机制

- 谁强制，强制谁

- 怎么强制：强制的手段

### 社会化机制

- 谁来社会化

  - 社会化的行动者
  
  - 不是单向的

- 怎么社会化

- 社会化的效应（特点）

### 多元机制

- 多种机制混合

- 补充而非替代



## 政策扩散方法路径

### 现象分析

### 机制分析

### 混合分析


# 现有不足与盲点（这一整块整合度很低）

## 解释的不足

### 谁扩散

- 内部参与者

  - 对决策者的联系关注不足（引出后文的干部交流）
  
  - 把决策者异质性关注的不足（引出后文的能力）
  
  - 对执行者关注的不足（引出后文的执行者）

- 外部参与者

  - 对民众关注不足（引出后文的回应之回应）
  
  - 对全球化的关注不足（引出后文的国际组织直接影响地方政府）

### 扩散什么

- 政策扩散使用二分的观点，对文本变化的关注不足（引出后文的政策再造）

- 过于关注政策采用而非政策制定（引出议程设置中的政策扩散，“会议政治”）

- 过于关注首次采用而非一个多次的互动方式

- 对政策本身关注的不足

- 对政策执行中的政策扩散关注不足

### 为什么扩散

- 对强制的自主性关注不足

- 对机制的整合不足

### 怎么扩散

## 使用的不足

## 方法的不足


# 未来方向：基于政治学视角 （这三部分都看不出对政治学的重要性）

## 作为因变量的政策扩散

### 国家能力与政策扩散研究

### 政府回应性与政策扩散研究

### 全球化与政策扩散研究

## 作为自变量的政策扩散

### 观察纵向政府间关系的窗口

### 观察横向政府间关系的窗口

### 观察国家社会关系的窗口

## 基于大数据方法的政策扩散研究

### 自然语言处理方法

### 社交网络分析方法

