---
output:
  bookdown::pdf_document2:
    keep_tex: true
    fig_caption: true
    latex_engine: xelatex
    number_sections: true
  bookdown::word_document2:
    reference_docx: "template_CHN.docx"
    keep_md: true
    number_sections: FALSE
knit: (function(inputFile, encoding) {rmarkdown::render(inputFile, encoding = encoding, output_format = c("bookdown::word_document2", "bookdown::pdf_document2")) })
documentclass: ctexart

always_allow_html: true

fontsize: 12pt
geometry: margin=1in
csl: "china-national-standard-gb-t-7714-2015-author-date.csl"
link-citations: true
colorlinks: true
toc: true
indent: true

editor_options: 
  markdown: 
    wrap: sentence

title: '政策扩散研究评述：理论、方法和进路'

author:
- 孙宇飞 2020312236^[清华大学政治学系2020级直博生，联系电话：18638750921，邮箱：sunyf20@mails.tsinghua.edu.cn]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
if (!require(pacman)) install.packages("pacman")
library(pacman)
p_load(grid,
       gridExtra,
       png,
       magick, 
       usmap,
       interplot,
       dotwhisker,
       modelsummary,
       # Visualization
       lubridate,
       # Applied
       broom,
       knitr,
       # dependency
       scales,
       tidyverse,
       drhutools,
       qs,
       kableExtra)
set.seed(19970921)
# Theme setup
theme_set(theme_minimal())
#Data input
```

\newpage

# 政治学基础

## 政治学理性主义、文化主义和结构主义的差异，基于一具体政治议题用三种视角阐释（2022年考博真题）

1.  本体论

本体论是指各研究范式或流派对世界"是什么"的界定。

理性主义：世界是由个体构成的，对集体的解释必须通过对个体的认知，对个体的理解则立基于对理性选择的目的进行的解释。

结构主义：结构主义在本体论上是整体主义的，认为世界是由结构这个实体构成的，结构决定着人们的认识和行为。
实体是根据与其他实体的关系而非通过它们自身的特性来加以定义的。与
理性主义和文化主义不同，结构主义否定了行动者本身的能动性并简化其假定。

文化主义：文化群体是构成世界的基本因素，它探讨主体间的和超个体的规范，认为同一群体的成员拥有共同的观念、倾向或看待世界的方式。
主体间的意识由认知与良知这两个要素构成。共
同的认知和良知构成了社群文化，进而构成了社会秩序的基本架构。
文化与社群还是个体与群体身份的基础，自我是在与他人的互动中发展起来的一个"社群之我"。与
理性主义不同，文化主义中的利益概念不完全是前定的，在很大程度上是有条件的、视情况而定的，它认为理智并不具有必然性和普遍性，理性思考的类别与理性的本质因文化而异。

2.  方法论

方法论是指各研究范式或流派认识和改造世界的一般方法，它是解决"怎么办"的工具。

理性主义方法论视个体为理智的思考者，将人们的爱好与信念植根于物质世界，将行动者作为思想实验的实施者。因
此，理性主义列出了针对思想实验的"决定性"证据，这些证据是可证伪、可观察的。理
性主义秉持定量方法和一种实证主义的科学哲学，并试图构建一种知识结构来对非理性行动进行解释。

文化主义通过对意义进行比较分析来理解事物。
由于意义是特定文化所特有的，所以文化主义主要进行案例研究，认为案例是独特的，个案的特征是由历史偶然性决定的，个体发展基本上是由不断 发生的历史偶然事件所决定的。所
以，文化分析路径对跨个案的概括持否定态度，反对通则研究。

结构主义通过把社会结构模式化来观察各结构之间的异同，据此把这些结构模式划分为不同的种类，从而使我们可以对这些特定的结构种类进行分 析和概括。由
于这种结构划分或结构种类有其特定的适用范围，既不是普遍主义的也不是特殊主义的， 所以，结构主义处于理性主义的普遍主义和文化主 义的特殊主义之间，它的分析单位通常处于全体与 个体、一般与特殊之间，是通过将个案划分为不同的 种类并建立起分类框架来达到概括目的的。所
以， 根据研究对象的内容与形式即特定结构种类进行分 类研究就是结构主义比较方法的基本特征。

理性主义否 定了价值与背景，文化主义否定了选择与约束，而结 构主义否定了行动与方向。

3.可能的融合

解释现代性

## 政党与国家社会关系（2020年考博真题）

参见"景跃进：将政党带进来------国家与社会关系范畴的反思与重构"[(景跃进, 2019)](http://govreform.cupl.edu.cn/info/1022/6780.htm)

## 比较早期中国和近代早期欧洲的国家建构，试分析为何二者走向大分流?

参见“王裕华：中国的国家兴衰：从盛唐到晚清”[(王裕华, 2020)](https://scholar.harvard.edu/files/yuhuawang/files/wang_yu_hua_.zhong_guo_de_guo_jia_xing_shuai_cong_sheng_tang_dao_wan_qing_final.pdf)

- 国家建构的三个任务

  - 国家机器:合法统治、职业化、去人格化、功绩制、文官政府
  
  - 国家能力(有效治理):强制力、建制力
  
  - 国家认同:去家族(社区)化、统一文教、制度认同
  
- 国家建构的理论解释

  - 国家中心论:国家对物质与非物质因素的需求
  
  - 社会中心论:社会结构、社会精英、宗教
  
  - 例外论
  
- 中国和西欧的国家建构

  - 西欧
    
    - 罗马帝国崩溃 - 封建制
    
    - 战争形式的改变 - 需要更多的物质资料发动战争 - 国家建构
    
    - 战争创造国家，国家发动战争
    
  - 中国
  
    - 国家能力
    
    - 国家精英与地方社会组织
    
      - 星状形网络（唐） -（小冰河期：黄巢起义杀门阀大族） 领结形网络（宋-鸦片战争爆发） -（鸦片战争：地方社会的军事化） 指环型网络（国家内卷化）
      
      - 变化动力：气候
      
  - 比较维度：战争、国家能力、精英结构/国家-社会关系、 国家认同、宗教/意识形态、国际关系、地理
  
## 数字时代的国家能力

参见“《信息政治学：理解数字时代国家治理的新视角》”[(孟天广, 2021)](https://www.dps.tsinghua.edu.cn/info/1197/2531.htm)

- 科技革命驱动政治文明发展

  - 第一次工业革命形成了以工具理性为基础的准科层制组织；
  
  - 第二次工业革命产生了韦伯意义上的科层制成为全球政府组织的主流形式；
  
  - 第三次工业革命促进了电子政务的产生，以无间隙政府、新公共管理等政府改革为标志对传统科层制组织形式进行了自我调适；
  
  - 随着以大数据和人工智能为代表的第四次工业革命的推进，整个人类社会正在经历一个“快速、大尺度、深层次”的数字化转型浪潮。“大尺度”意味着这种数字化转型是全球范围的数字化，而不是个别区域的数字化。“深层次”反映了新技术对人类社会组织方式、运行机理和价值体系有革命性影响，而非仅仅影响表层现象，譬如数字与智能技术已经在深刻地变革着人们的社交、交易方式，甚至重构着人们与政府互动的方式。
  
- 信息政治学的理论视角

  - 信息问题自古以来就是国家治理的一个关键问题：国家治理过程中信息生产、信息汲取、信息扩散、信息处理乃至信息使用的原则与逻辑
  
  - 国家内部的信息问题
  
    - 委托代理关系导致的信息问题：上下级政府间的信息不对称、信息碎片化以及各部门之间的信息壁垒
    
    - 信息处理问题，如政府如何从有限信息中发现经济社会运行的规律等
    
  - 国家与社会进行信息交换的问题
  
    - 包容性制度：国家与社会之间的信息机制
    
      - 在国家与社会之间畅通信息，构建国家—社会信息传输和交换体系，提升国家的信息汲取能力
      
      - 如何加总、筛选社会偏好的问题，如谁的偏好或者哪些偏好应该排在优先位置，如何最有效地识别、加总和筛选公共需求，使其进入政治议程
    
    - 公共空间建设

- 数字时代的国家信息能力

  - 国家治理需要具备国家信息能力。
  
    - 信息要素重要。
    
      - 现代国家治理体系中，治理主体日益复杂多元，只有信息要素可以把多元主体联系起来形成一个动态系统，依靠信息机制来实现国家与社会、社会内部的合作与协同。
      
      - 信息就成为国家决策、政府感知社会、政府与社会沟通、政策评估、政治问责和政治传播的核心机制。因此，国家治理需要具备国家信息能力。
  
  - 国家信息能力的来源。
  
    - “赋权社会”
    
    - “赋能政府”
    
  - 国家信息能力的构成
  
    - 信息稀缺：信息汲取能力：“自上而下”督察、巡视和“自下而上”群众路线、网络问政相结合的信息汲取机制
    
    - 信息过载：信息处理能力
    
      - 行政机制
      
      - 社群机制
      
## 比较共和制和民主制两种政体

- 宪政

  - 君主制
  
  - 共和制
  
    - 民主共和
    
    - 贵族共和
  
  - 民主制

- 独裁

  - 獨裁專制
  
  - 寡頭專制
  
  - 群體暴政
  
- 强调的重点不同

  - 民主制：平等多数
  
  - 共和制：各方平衡

- 强调的阶级不同

  - 共和制更能接受精英政治
  
- 政治参与的程度不同

- 权力来源不同

共和制國家的權力來源也只是少數人，而民主制國家的權力來源於所有人。

民主制看成是共和制的一個特例。

## 我们为什么需要民主决策

## 不平等如何影响民主转型

## 社会资本如何影响民主制度的运行

## 就第三波民主化浪潮而言，现代化理论是否仍然是最有力的解释？请结合一定案例或数据回答该问题

## 数字技术如何影响国家-社会关系

- 双向赋权，但有数字鸿沟

- 数字时代国家演变

- 数字时代国家能力：生产、汲取、处理、决策

  - 内部：信息汲取能力;数据治理能力;循证决策能力
  
  - 外部：数字规制能力;吸纳回应能力;濡化能力

## 全过程人民民主

## 政治文化

## 杨老师


# 近两年考博真题

## 2021年

## 2020年

## 2019年

## 苏毓淞老师

# 我导儿：政治文化

## 结构主义、理性选择、文化主义

当代比较政治中的三大研究范式即理性主义、文化主义和结构主义。

## 三代政治文化理论

政治文化是一组态度、信仰和情感，它赋予政治过程以秩序和含义，并提供一种基本的假设和规则用以规范政治体系中的行为。政
治文化是对政治中心理和主观层面的一种集合形式的和表述。

1.  基准公民文化（Almond&Verba, 1963）

贡献

公民文化的概念（理论）。一
个社会存着三种政治文化的观点。这
三种文化是：村民文化、臣民文化、参与者文化。他
认为，公民文化应该是这三种文化的混合。他
认为一个民主制度，若无公民文化的支撑，便无法常久。"
积极的、也是消极的；卷入的，也是不太卷入的；有影响力的，也是服从的。"

文化-政权关系的类型学（经验）。

-   政权决定于人的态度；

-   过多的参与、效忠或超脱都有助于民主；

-   美国是"最好的"。

跨国比较操作（方法）。

不足

-   准确么？文
    化是什么以及文化如何影响政治

-   对民主好么？民
    主悖论：公民文化太多太少都是坏事

-   精英的还是大众的

对文化主义整体的批判：

-   文化是确定性的

-   阶级结构决定态度

-   理性行为可以解释跨文化差异

2.  后物质主义文化

受到理性选择理论的攻击

《政治文化的复兴》

生活满意度和民主稳定性；人际信任和民主稳定性；对变革的态度。

随着西方发达工业国家1973-1988年间的经济社会发展，大众的价值观念发生了重大的变化，从物质主义转向到后物质主义

物质主义：经济安全、人身安全；后物质主义：归属于自尊、审美与知识。

生存价值观-幸福价值观；传统权威-世俗理性权威。

-   社会经济发展带来了世俗主义和自我表达；

-   看不到全球文化融合

-   文化变迁是一个非线性过程

-   现代化不等于西化

3.  公民文化的挑战：概念化

（1）定义不一致

Alomnd & Verba: 态度；Inglehart: 习惯；Eckstein: 方向，文化主题

（2）谁的文化

-   精英与大众

-   制度与文化

(1)如何定义概念； (2) 如何从一个社会的整体政治文化中分离亚文化（例如精英​​政治文化）； (3)如何整合构成概念的众多个体层面的取向； (4) 如何从个体层面的成分创建社会层面的变量； (5) 如果上述已经解决，如何衡量这个概念； (6) 如何从所研究的主观取向中推导出关于个人政治行为的假设； (7) 政治文化如何与制度和政体的其他属性相互作用，以产生对某些类型的政治结果的倾向。
Pye 1965：制度历史塑造大众文化

Almond and Power 1992：文化是输入和输出的媒介

解决方案

-   Rubic：同意我们在谈论不同的事情

-   共享性：只关注不同社会的同一部分

-   社会层面：社会属性，但失去连接个人和环境的层面

4.  公民文化的挑战：操作化

从个人如何到社会

-   机制（大脑和信息之间的诱发过程）

-   复杂性（整个社会中单个个体的复杂结构）

-   宇宙谬误（从个体、集合、模式、系统中推导出结论---毫无意义）；文化爱好者争论民族性格，但做类似的事情

## 政治文化与中国

1.群众路线和西方民主之间的不同：

-   西方民主: 民主由专门设计的制度和规则组成；

-   极权主义：极权主义追求国家对社会的全面控制；

-   公民社会：是自治的，不受国家控制。

群众路线是建立在国家和社会之间全面互动的基础上的控制；

2.群众路线的功能

国家和社会关系：国家和社会之间的直接联系，中间组织和机构的干预最少

动员体制：彻底发动群众参政

隐含的社会契约：一种隐含的社会契约概念，其中精英为群众的利益服务，而群众反过来为国家提供政治支持

-   连续性政治垄断

    -   只有合法执政党：没有选举挑战

    -   马列主义+民族主义

    -   媒体控制+异议人士镇压

    -   鼓励系统内直接民众参与

-   更新群众路线

    -   大规模的群众运动

-   人口统计学的连续性

    -   年龄和经历

3.  对一般理论的回应

-   国家能力

-   先进治理（世界先进、人事任用、政策、公共服务等）

-   机构

# 杨雪冬老师

## 全球化与地方治理

### 请根据你对文献的评价，给出你关于政治发展的定义

### 各国有选择自己制度和道路的权利，但这种选择会受到哪些因素的影响？

### 在全球化时代，各国政治发展要解决的首要问题是什么？

# 张小劲老师

## 比较政治学

### 课件

### 期末作业

## 近期发表

# 孟天广老师

## 考博真题

## 近期发表

## 国家

-   什么是国家?

    -   马克思：阶级统治的暴力机器

    -   霍布斯：利维坦(国家)防止战争状态

    -   吉登斯：国家的统治在地域上是有章可循的，而且还能动员暴力工具来维护统治

    -   韦伯：明确的边界、对暴力的垄断权、国家具有自主性、专业化的官僚机构、合法的统治

    -   斯考切波：国家可以看做是拥有对领土和居民控制权的组织, 它可以系统地表达和推进自己的目标, 而不是简单地 反映集团 、阶级或社会需求与利益

    -   奥尔森：掠夺性的，坐寇

    -   诺斯：暴力潜能分配理论

-   国家类型

-   

### 国家的类型

### 国家建构:国家如何形成?

### 国家能力:国家有效治理的奥秘 5. 国家认同:国家如何团结?

# 张开平老师

## 政治学导论：政治传播

# 刘瑜老师

# 于晓虹老师
